

all: test alloc free maxout

test: test.c
	gcc -o test test.c

alloc: alloc.c
	gcc -o alloc alloc.c

free: free.c
	gcc -o free free.c

maxout: maxout.c
	gcc -o maxout maxout.c

clean:
	rm test alloc maxout free